name: build-windows
on: [push, workflow_dispatch]
defaults:
  run:
    shell: bash -l {0}
env:
  CHERE_INVOKING: 1
  CYGWIN_NOWINPATH: 1
  SHELLOPTS: igncr

jobs:
  c:
    name: windows-2022 / C
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: cygwin/cygwin-install-action@v4
        with:
          packages: cmake gcc-core make pkgconf
      - run: ./run.sh
      - run: cd tests && make && ./tests
      - run: cd benchmarks && make && ./benchmarks
  python:
    name: windows-2022 / Python
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: cygwin/cygwin-install-action@v4
        with:
          packages: gcc-core python3 python3-devel python3-pip
      - run: python3 -m pip install -v .
      - run: python3 examples/Python/thread-safe.py
      - run: python3 benchmarks/benchmarks.py
