name: build-unix
on: [push, workflow_dispatch]
env:
  LD_LIBRARY_PATH: /usr/local/lib
  PKG_CONFIG_PATH: /usr/local/share/pkgconfig

jobs:
  c:
    name: ${{ matrix.os }} / C
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh
      - run: cd tests && make && ./tests
      - run: cd benchmarks && make && ./benchmarks
  python:
    name: ${{ matrix.os }} / Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install .
      - run: python3 examples/Python/thread-safe.py
      - run: python3 benchmarks/benchmarks.py
