name: c-build-test
on: [push, workflow_dispatch]
defaults:
  run:
    shell: bash

jobs:
  c-build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh
      - run: cd tests && make && ./tests
