name: unix
on: [push, workflow_dispatch]
env:
  LD_LIBRARY_PATH: /usr/local/lib
  PKG_CONFIG_PATH: /usr/local/share/pkgconfig

jobs:
  c_macos:
    name: macos-12 / C
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh
      - run: cd tests && CC=gcc-13 make && ./tests
  c_linux:
    name: ubuntu-22.04 / C
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./run.sh
      - run: cd tests && make && ./tests
  python:
    name: ${{ matrix.os }} / Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install .
      - run: python3 examples/Python/thread-safe.py
