name: winbuild
on: [push, workflow_dispatch]
defaults:
  run:
    shell: msys2 {0}

jobs:
  c:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          pacboy: cmake:p gcc:p make:p
      - run: ./run.sh
      - run: PKG_CONFIG_PATH=/usr/local/share/pkgconfig cd tests && mingw32-make && ./tests
